# Generated by Django 2.1.1 on 2018-09-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('user', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('public_repo', models.IntegerField()),
                ('created', models.DateTimeField(default=None)),
                ('followers', models.IntegerField(default=None)),
                ('following', models.IntegerField(default=None)),
            ],
        ),
    ]
